### ISSUE TITLE
Floating point in the stake amount input

### ISSUE THREAD

**Issue by miohtama** [yam-finance/yam-protocol#21]
Trying to input a number like 1000 LEND results to a BigNumber conversion error.

![image](https://user-images.githubusercontent.com/49922/89941905-f9b77900-dc1b-11ea-99b8-410287ca8711.png)

This is because somewhere there is 1000 * 10^18 calculated in a floating point.

Never use floating point math with token amounts. Happy to see BigNumber lib catching this error.

![image](https://user-images.githubusercontent.com/49922/89941878-f2906b00-dc1b-11ea-96e5-548948aa009e.png)

**Comment by miohtama** [comment]
Looks like there is a PR already open https://github.com/yam-finance/yam-protocol/pull/20

**Comment by brockelmore** [comment]
closed #20
