### ISSUE TITLE
Stake with YFI: Error "Fail with error 'SafeERC20: low-level call failed'"

### ISSUE THREAD

**Issue by dankrad** [yam-finance/yam-protocol#23]
This is the error as reported on Etherscan. I have not attempted a detailed stacktrace. Not giving my own transaction ID for privacy reasons, please contact using PM for this. But many transactions fail with the same reason: https://etherscan.io/txs?a=0xc5b6488c7d5bed173b76bd5dca712f45fb9eaeab&f=1

**Comment by dankrad** [comment]
(another common error is "Cannot withdraw 0", but here is one with the error I mentioned as an example: https://etherscan.io/tx/0x33cc007e62a4de96d511128e5b55e7713c5299597a7f8684c208f501ae6c4f41

**Comment by sharma409** [comment]
should be fixed by #26 — it's a rounding error in the max function

**Comment by brockelmore** [comment]
#26
