### ISSUE TITLE
Moving from YAM 1.0 to YAM 2.0

### ISSUE THREAD

**Issue by ayumi-cloud** [yam-finance/yam-protocol#68]
Many people are all asking the same question, can they move their YAM 1.0 tokens over to YAM 2.0 if the project goes ahead and how will this be done. People have suggested an Airdrop for YAM 1.0 Token holders.

**It would be useful to the community to let them know!**

Likewise, if such an airdrop was to happen in the near future, would the authors create an online form (e.g. Google Forms) where users could send them their Ethereum addresses, along with their token balances - so their tokens could get auto updated to YAM 2.0 quickly and easily.

**Comment by tr007008** [comment]
I think some good follow-ups to this question would be:  
1. is there any advantage/danger to leaving funds locked up in the contract?  
2. I'm still earning YAM and I haven't harvested/withdrawn anything yet.  Should I do something different?
3. If we continue to earn YAM will the ones earned after the demise of v1  also be matched in the change over?

**Comment by ayumi-cloud** [comment]
Instead of opening another issue, just going to write a couple of questions here:

1. Adding upper price limits.

Centralized exchanges by law have in-built circuit breakers to stop flash crashes! When the `rebase` occurred for the first time the price jumped down 80% (second one made price down to 90%). Surely there should be some kind of upper limit - say up to a max of a 10% price change when a `rebase` happens. Because of this flash crash, many people thought you guys did an exit scam. But I think the real reason is because there were no limits for price changes from a `rebase` are setup. Having a limit would stop a flash crash and give time for the dev's to fix any future issues.

2. Supply in the future.

Reading tr007008 comment got me thinking, what is going to happen in the future? For example, YAM 1.0 seems to be creating a crazy supply which is growing every day. The supply number is hanging out of the ertherscan website display window at the moment. I was wondering in 20 years time, if Yam 1.0 is still running, would someone just buy $10 of yam and Yam 1.0 gives them 1 trillion yams at the price of $1.  The people in the future must be thanking this team! My thinking is surely there should be a max growth creation limit built into the code for the supply grow amount.

Just curious on these two things.

Wish this project good luck and look forward to a V2.
